version: '3.9'

services:
  test-database:
    image: postgres:14
    restart: always
    container_name: e2e-tests
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
