version: '3.9'

services:
  database:
    image: postgres:14
    restart: always
    container_name: integration-tests
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
